# Generated by Django 5.2.4 on 2025-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
