# Generated by Django 5.2.4 on 2025-10-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_claimrequest_is_trashed_claimrequest_trashed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='is_trashed',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='trashed_at',
        ),
    ]
